version: "3.9"
services:
  node_web:
    depends_on:
      - "local_database"
    build: .
    ports:
      - "80:80"
    volumes:
      - ./:/usr/src/app/
  local_database:
    platform: linux/x86_64
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_PASSWORD: "user"
      MYSQL_DATABASE: "user"
    ports:
      - "3306:3306"
    volumes:
      - ${DB_VOLUME}:/var/lib/mysql